name: Deploy Backend Application

on:
    push:
        branches: [master]
        paths:
            - 'ToDoListApp.Server/**'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '10.0.x'
            
            - name: Publish
              working-directory: ToDoListApp.Server
              env:
                ASPNETCORE_ENVIRONMENT: Development
                ConnectionStrings__DefaultConnection: "Server=localhost;Database=dummy;Trusted_Connection=True;"
              run: dotnet publish --configuration Release --output ./publish
            
            - name: Deploy
              uses: azure/webapps-deploy@v3
              with:
                app-name: 'app-todolistapp-prod'
                publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                package: ./ToDoListApp.Server/publish

    
